// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ros_bridge_conf.proto

#include "ros_bridge_conf.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace apollo {
namespace cyber {
PROTOBUF_CONSTEXPR BridgeConf::BridgeConf(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.converter_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BridgeConfDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BridgeConfDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BridgeConfDefaultTypeInternal() {}
  union {
    BridgeConf _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BridgeConfDefaultTypeInternal _BridgeConf_default_instance_;
PROTOBUF_CONSTEXPR PluginDeclareInfo::PluginDeclareInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct PluginDeclareInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PluginDeclareInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PluginDeclareInfoDefaultTypeInternal() {}
  union {
    PluginDeclareInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PluginDeclareInfoDefaultTypeInternal _PluginDeclareInfo_default_instance_;
}  // namespace cyber
}  // namespace apollo
static ::_pb::Metadata file_level_metadata_ros_5fbridge_5fconf_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ros_5fbridge_5fconf_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ros_5fbridge_5fconf_2eproto = nullptr;

const uint32_t TableStruct_ros_5fbridge_5fconf_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::apollo::cyber::BridgeConf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::apollo::cyber::BridgeConf, _impl_.converter_),
  PROTOBUF_FIELD_OFFSET(::apollo::cyber::PluginDeclareInfo, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::apollo::cyber::PluginDeclareInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::apollo::cyber::PluginDeclareInfo, _impl_.type_),
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::apollo::cyber::BridgeConf)},
  { 7, 14, -1, sizeof(::apollo::cyber::PluginDeclareInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::apollo::cyber::_BridgeConf_default_instance_._instance,
  &::apollo::cyber::_PluginDeclareInfo_default_instance_._instance,
};

const char descriptor_table_protodef_ros_5fbridge_5fconf_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025ros_bridge_conf.proto\022\014apollo.cyber\"@\n"
  "\nBridgeConf\0222\n\tconverter\030\001 \003(\0132\037.apollo."
  "cyber.PluginDeclareInfo\"!\n\021PluginDeclare"
  "Info\022\014\n\004type\030\001 \001(\t"
  ;
static ::_pbi::once_flag descriptor_table_ros_5fbridge_5fconf_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ros_5fbridge_5fconf_2eproto = {
    false, false, 138, descriptor_table_protodef_ros_5fbridge_5fconf_2eproto,
    "ros_bridge_conf.proto",
    &descriptor_table_ros_5fbridge_5fconf_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_ros_5fbridge_5fconf_2eproto::offsets,
    file_level_metadata_ros_5fbridge_5fconf_2eproto, file_level_enum_descriptors_ros_5fbridge_5fconf_2eproto,
    file_level_service_descriptors_ros_5fbridge_5fconf_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ros_5fbridge_5fconf_2eproto_getter() {
  return &descriptor_table_ros_5fbridge_5fconf_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ros_5fbridge_5fconf_2eproto(&descriptor_table_ros_5fbridge_5fconf_2eproto);
namespace apollo {
namespace cyber {

// ===================================================================

class BridgeConf::_Internal {
 public:
};

BridgeConf::BridgeConf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:apollo.cyber.BridgeConf)
}
BridgeConf::BridgeConf(const BridgeConf& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BridgeConf* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.converter_){from._impl_.converter_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.BridgeConf)
}

inline void BridgeConf::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.converter_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BridgeConf::~BridgeConf() {
  // @@protoc_insertion_point(destructor:apollo.cyber.BridgeConf)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BridgeConf::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.converter_.~RepeatedPtrField();
}

void BridgeConf::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BridgeConf::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.BridgeConf)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.converter_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BridgeConf::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .apollo.cyber.PluginDeclareInfo converter = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_converter(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BridgeConf::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.BridgeConf)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.cyber.PluginDeclareInfo converter = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_converter_size()); i < n; i++) {
    const auto& repfield = this->_internal_converter(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.BridgeConf)
  return target;
}

size_t BridgeConf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.BridgeConf)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .apollo.cyber.PluginDeclareInfo converter = 1;
  total_size += 1UL * this->_internal_converter_size();
  for (const auto& msg : this->_impl_.converter_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BridgeConf::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BridgeConf::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BridgeConf::GetClassData() const { return &_class_data_; }


void BridgeConf::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BridgeConf*>(&to_msg);
  auto& from = static_cast<const BridgeConf&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.BridgeConf)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.converter_.MergeFrom(from._impl_.converter_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BridgeConf::CopyFrom(const BridgeConf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.BridgeConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BridgeConf::IsInitialized() const {
  return true;
}

void BridgeConf::InternalSwap(BridgeConf* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.converter_.InternalSwap(&other->_impl_.converter_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BridgeConf::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ros_5fbridge_5fconf_2eproto_getter, &descriptor_table_ros_5fbridge_5fconf_2eproto_once,
      file_level_metadata_ros_5fbridge_5fconf_2eproto[0]);
}

// ===================================================================

class PluginDeclareInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<PluginDeclareInfo>()._impl_._has_bits_);
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

PluginDeclareInfo::PluginDeclareInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:apollo.cyber.PluginDeclareInfo)
}
PluginDeclareInfo::PluginDeclareInfo(const PluginDeclareInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PluginDeclareInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_type()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.PluginDeclareInfo)
}

inline void PluginDeclareInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PluginDeclareInfo::~PluginDeclareInfo() {
  // @@protoc_insertion_point(destructor:apollo.cyber.PluginDeclareInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PluginDeclareInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
}

void PluginDeclareInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PluginDeclareInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.PluginDeclareInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.type_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PluginDeclareInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "apollo.cyber.PluginDeclareInfo.type");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PluginDeclareInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.PluginDeclareInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "apollo.cyber.PluginDeclareInfo.type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.PluginDeclareInfo)
  return target;
}

size_t PluginDeclareInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.PluginDeclareInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string type = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PluginDeclareInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PluginDeclareInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PluginDeclareInfo::GetClassData() const { return &_class_data_; }


void PluginDeclareInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PluginDeclareInfo*>(&to_msg);
  auto& from = static_cast<const PluginDeclareInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.PluginDeclareInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_type()) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PluginDeclareInfo::CopyFrom(const PluginDeclareInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.PluginDeclareInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PluginDeclareInfo::IsInitialized() const {
  return true;
}

void PluginDeclareInfo::InternalSwap(PluginDeclareInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PluginDeclareInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ros_5fbridge_5fconf_2eproto_getter, &descriptor_table_ros_5fbridge_5fconf_2eproto_once,
      file_level_metadata_ros_5fbridge_5fconf_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace cyber
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::apollo::cyber::BridgeConf*
Arena::CreateMaybeMessage< ::apollo::cyber::BridgeConf >(Arena* arena) {
  return Arena::CreateMessageInternal< ::apollo::cyber::BridgeConf >(arena);
}
template<> PROTOBUF_NOINLINE ::apollo::cyber::PluginDeclareInfo*
Arena::CreateMaybeMessage< ::apollo::cyber::PluginDeclareInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::apollo::cyber::PluginDeclareInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
